import Footer from "@/components/Footer"
import Header from "@/components/Header"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({
	subsets: ["latin"],
	display: "block",
	variable: "--font-inter",
})

export const metadata: Metadata = {
	title: {
		template: "%s | Daisy App Router",
		default: "Daisy App Router",
	},
	description:
		"Generated by create next app, using tailwind, daisyUI & the app router.",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang="en"
			data-theme="dark"
			className={`${inter.variable} antialiased`}
			suppressHydrationWarning
		>
			<body className="flex min-h-screen w-full flex-col bg-slate-950">
				<Header />
				<main className="mt-16 flex w-full flex-1 flex-col overflow-auto">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	)
}
